apiVersion: apps/v1
kind: Deployment
metadata:
  name: techdome-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techdome-frontend
  template:
    metadata:
      labels:
        app: techdome-frontend
    spec:
      containers:
      - name: techdome-frontend
        image: pasupathikumar819/techdome-frontend:latest
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: techdome-frontend
spec:
  type: LoadBalancer
  selector:
    app: Techdome-frontend
  ports:
    - port: 5000
      targetPort: 5000
